# Generated by Django 3.0.3 on 2020-02-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geniusdennis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_eng', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spanish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_esp', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.DeleteModel(
            name='EnglishWord',
        ),
        migrations.DeleteModel(
            name='SpanishWord',
        ),
        migrations.AddField(
            model_name='english',
            name='spanish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusdennis.Spanish'),
        ),
    ]
