# Generated by Django 3.0.3 on 2020-02-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusdennis', '0002_auto_20200222_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
